### ISSUE TITLE
Error adding targets 

### ISSUE THREAD

**Issue by bodagovsky** [fluffyemily/cross-platform-rust#43]
I've met some issues trying to add targets for rustup

```rustup target add armv7-apple-ios
error: component 'rust-std' for target 'armv7-apple-ios' is unavailable for download for channel stable
error: component 'rust-std' for target 'armv7s-apple-ios' is unavailable for download for channel stable
error: component 'rust-std' for target 'i386-apple-ios' is unavailable for download for channel stable
```
only 2 targets passed
`x86_64-apple-ios` and `aarch64-apple-ios`

**Comment by fluffyemily** [comment]
Hi @bodagovsky. I think this may be due to the Rust team reducing support for Apple 32 bit architectures earlier this year. https://blog.rust-lang.org/2020/01/03/reducing-support-for-32-bit-apple-targets.html.

I shall update the documentation to remove references to 32 bit archs. Thanks for helping me keep this up to date. I have not been developing in Rust for a while now so am no longer keeping track of changes.
